# Generated by Django 3.2.13 on 2022-08-03 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemetryLogMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("exception_name", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("traceback", models.TextField()),
                ("enhydris_version", models.TextField()),
                ("enhydris_commit_id", models.CharField(max_length=40)),
                (
                    "telemetry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telemetry.telemetry",
                    ),
                ),
            ],
            options={
                "ordering": ["telemetry", "-timestamp"],
            },
        ),
    ]
