# Generated by Django 3.2.13 on 2022-10-17 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0005_addupi"),
    ]

    operations = [
        migrations.RenameField(
            model_name="telemetry",
            old_name="data_time_zone",
            new_name="data_timezone",
        ),
        migrations.RenameField(
            model_name="telemetry",
            old_name="fetch_offset_time_zone",
            new_name="fetch_offset_timezone",
        ),
    ]
