# Generated by Django 5.2.4 on 2025-09-10 10:59

from django.db import migrations, models

import enhydris.telemetry.models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0010_alter_telemetry_data_timezone_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="sensor_id",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="telemetry",
            name="type",
            field=models.CharField(
                choices=enhydris.telemetry.models._get_type_choices,
                help_text="The type of the system from which the data is to be fetched. If unlisted, it might mean that it is currently unsupported.",
                max_length=30,
                verbose_name="Telemetry system type",
            ),
        ),
    ]
