# Generated by Django 5.2.8 on 2025-11-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0011_alter_sensor_sensor_id_alter_telemetry_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telemetry",
            name="password",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="telemetry",
            name="remote_station_id",
            field=models.CharField(blank=True),
        ),
    ]
