# Generated by Django 2.1.5 on 2019-02-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("enhydris", "0008_join_alt_fields")]

    operations = [
        migrations.RemoveField(model_name="eventtype", name="descr_alt"),
        migrations.RemoveField(model_name="filetype", name="descr_alt"),
        migrations.RemoveField(model_name="gentity", name="name_alt"),
        migrations.RemoveField(model_name="gentity", name="remarks_alt"),
        migrations.RemoveField(model_name="gentity", name="short_name_alt"),
        migrations.RemoveField(model_name="gentityaltcodetype", name="descr_alt"),
        migrations.RemoveField(model_name="gentityevent", name="report_alt"),
        migrations.RemoveField(model_name="gentityfile", name="descr_alt"),
        migrations.RemoveField(model_name="gentityfile", name="remarks_alt"),
        migrations.RemoveField(model_name="instrument", name="name_alt"),
        migrations.RemoveField(model_name="instrument", name="remarks_alt"),
        migrations.RemoveField(model_name="instrumenttype", name="descr_alt"),
        migrations.RemoveField(model_name="intervaltype", name="descr_alt"),
        migrations.RemoveField(model_name="lentity", name="remarks_alt"),
        migrations.RemoveField(model_name="organization", name="acronym_alt"),
        migrations.RemoveField(model_name="organization", name="name_alt"),
        migrations.RemoveField(model_name="person", name="first_name_alt"),
        migrations.RemoveField(model_name="person", name="initials_alt"),
        migrations.RemoveField(model_name="person", name="last_name_alt"),
        migrations.RemoveField(model_name="person", name="middle_names_alt"),
        migrations.RemoveField(model_name="stationtype", name="descr_alt"),
        migrations.RemoveField(model_name="timeseries", name="name_alt"),
        migrations.RemoveField(model_name="timeseries", name="remarks_alt"),
        migrations.RemoveField(model_name="timestep", name="descr_alt"),
        migrations.RemoveField(model_name="unitofmeasurement", name="descr_alt"),
        migrations.RemoveField(model_name="variable", name="descr_alt"),
    ]
