# Generated by Django 2.1.8 on 2019-04-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("enhydris", "0010_change_verbose_names")]

    operations = [
        migrations.AlterField(
            model_name="gentityevent",
            name="user",
            field=models.CharField(blank=True, max_length=64),
        )
    ]
