# Generated by Django 2.2.2 on 2019-06-04 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("enhydris", "0011_gentity_event_user_optional")]

    operations = [
        migrations.RenameField(
            model_name="gpoint", old_name="srid", new_name="original_srid"
        ),
        migrations.RemoveField(model_name="gpoint", name="approximate"),
        migrations.RemoveField(model_name="gpoint", name="asrid"),
    ]
