# Generated by Django 2.2.3 on 2019-08-16 12:31

import django.db.models.deletion
from django.db import migrations, models

import parler.fields
import parler.models

from .helpers.parler import Migrator


def move_stationtype_descr(apps, schema_editor):
    Migrator(apps, schema_editor, "StationType").migrate()


def reverse_move_stationtype_descr(apps, schema_editor):
    Migrator(apps, schema_editor, "StationType").reverse_migrate()


class Migration(migrations.Migration):

    dependencies = [("enhydris", "0014_translatable_variable")]

    operations = [
        migrations.CreateModel(
            name="StationTypeTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("descr", models.CharField(blank=True, max_length=200)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="enhydris.StationType",
                    ),
                ),
            ],
            options={
                "verbose_name": "station type Translation",
                "db_table": "enhydris_stationtype_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
        ),
        migrations.RunPython(move_stationtype_descr, reverse_move_stationtype_descr),
        migrations.AlterModelOptions(name="stationtype", options={}),
        migrations.RemoveField(model_name="stationtype", name="descr"),
    ]
