# Generated by Django 2.2.4.dev20190704113610 on 2019-08-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("enhydris", "0015_translatable_stationtype")]

    operations = [
        migrations.AlterField(
            model_name="timeseries",
            name="precision",
            field=models.SmallIntegerField(
                default=2,
                help_text=(
                    "The number of decimal digits to which the values of the time "
                    "series will be rounded. It's usually positive, but it can be "
                    "zero or negative; for example, for humidity it is usually zero; "
                    "for wind direction in degrees, depending on the sensor, you "
                    "might want to specify precision -1, which means the value "
                    "will be 10, or 20, or 30, etc. This only affects the rounding "
                    "of values when the time series is retrieved; values are always "
                    "stored with all the decimal digits provided."
                ),
            ),
            preserve_default=False,
        )
    ]
