# Generated by Django 2.2.4 on 2019-08-19 14:16

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("enhydris", "0016_precision")]

    operations = [UnaccentExtension()]
