# Generated by Django 2.2.4 on 2019-08-23 21:56

from django.db import migrations


def check_gentity_alt_code_is_empty(apps, schema_editor):
    GentityAltCode = apps.get_model("enhydris", "GentityAltCode")
    if GentityAltCode.objects.exists():
        raise RuntimeError(
            "GentityAltCode has been abolished, and upgrading involves deleting "
            "the database table. In this case, the table appears to have data. "
            "Cowardly refusing to proceed. Manually delete the contents of the table, "
            "then try again."
        )


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("enhydris", "0017_unaccent")]

    operations = [
        migrations.RunPython(check_gentity_alt_code_is_empty, do_nothing),
        migrations.DeleteModel(name="GentityAltCode"),
        migrations.DeleteModel(name="GentityAltCodeType"),
    ]
