# Generated by Django 2.2.4 on 2019-08-23 22:29

import django.db.models.deletion
from django.db import migrations, models

import parler.fields
import parler.models

from .helpers.parler import Migrator


def move_timestep_descr(apps, schema_editor):
    Migrator(apps, schema_editor, "TimeStep").migrate()


def reverse_move_timestep_descr(apps, schema_editor):
    Migrator(apps, schema_editor, "TimeStep").reverse_migrate()


class Migration(migrations.Migration):

    dependencies = [("enhydris", "0018_remove_gentity_alt_code")]

    operations = [
        migrations.CreateModel(
            name="TimeStepTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("descr", models.CharField(blank=True, max_length=200)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="enhydris.TimeStep",
                    ),
                ),
            ],
            options={
                "verbose_name": "time step Translation",
                "db_table": "enhydris_timestep_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
        ),
        migrations.RunPython(move_timestep_descr, reverse_move_timestep_descr),
        migrations.AlterModelOptions(name="timestep", options={}),
        migrations.RemoveField(model_name="timestep", name="descr"),
    ]
