# Generated by Django 2.2.7 on 2020-02-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris", "0030_abolish_instruments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unitofmeasurement", options={"ordering": ["symbol"]}
        ),
    ]
