# Generated by Django 2.2.7 on 2020-03-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris", "0035_timeseriesrecord_constraints_and_indexes"),
    ]

    operations = [
        migrations.RemoveField(model_name="timeseries", name="datafile"),
        migrations.RemoveField(model_name="timeseries", name="end_date_utc"),
        migrations.RemoveField(model_name="timeseries", name="start_date_utc"),
    ]
