# Generated by Django 2.2.12 on 2020-10-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris", "0037_timeseries_groups"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
