# Generated by Django 2.2.16 on 2020-10-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris", "0101_squashed"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="timeseries",
            name="only_one_raw_timeseries_per_group",
        ),
        migrations.AddConstraint(
            model_name="timeseries",
            constraint=models.UniqueConstraint(
                condition=models.Q(type__in=(100, 150)),
                fields=("timeseries_group",),
                name="only_one_raw_or_processed_timeseries_per_group",
            ),
        ),
    ]
