# Generated by Django 2.2.17 on 2020-12-01 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris", "0102_unique_raw_and_processed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventtype",
            options={
                "verbose_name": "Log entry type",
                "verbose_name_plural": "Log entry types",
            },
        ),
        migrations.AlterModelOptions(
            name="garea",
            options={"verbose_name": "Area", "verbose_name_plural": "Areas"},
        ),
        migrations.AlterModelOptions(
            name="gareacategory",
            options={
                "verbose_name": "Area category",
                "verbose_name_plural": "Area categories",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ("name",),
                "verbose_name": "Organization",
                "verbose_name_plural": "Organization",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ("last_name", "first_name"),
                "verbose_name": "Person",
                "verbose_name_plural": "Persons",
            },
        ),
        migrations.AlterModelOptions(
            name="station",
            options={"verbose_name": "Station", "verbose_name_plural": "Stations"},
        ),
        migrations.AlterModelOptions(
            name="timeseriesgroup",
            options={
                "verbose_name": "Time series group",
                "verbose_name_plural": "Time series groups",
            },
        ),
        migrations.AlterModelOptions(
            name="timeseriesrecord",
            options={
                "get_latest_by": "timestamp",
                "managed": False,
                "verbose_name": "Time series record",
                "verbose_name_plural": "Time series records",
            },
        ),
        migrations.AlterModelOptions(
            name="timezone",
            options={
                "ordering": ("utc_offset",),
                "verbose_name": "Time zone",
                "verbose_name_plural": "Time zones",
            },
        ),
        migrations.AlterModelOptions(
            name="unitofmeasurement",
            options={
                "ordering": ["symbol"],
                "verbose_name": "Unit of measurement",
                "verbose_name_plural": "Units of measurement",
            },
        ),
        migrations.AlterModelOptions(
            name="variable",
            options={"verbose_name": "Variable", "verbose_name_plural": "Variables"},
        ),
        migrations.AlterModelOptions(
            name="variabletranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Variable Translation",
            },
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="descr",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="garea",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enhydris.GareaCategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="gareacategory",
            name="descr",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="gentity",
            name="code",
            field=models.CharField(blank=True, max_length=50, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="gentity",
            name="name",
            field=models.CharField(blank=True, max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="gentity",
            name="remarks",
            field=models.TextField(blank=True, verbose_name="Remarks"),
        ),
        migrations.AlterField(
            model_name="gentityevent",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="gentityevent",
            name="report",
            field=models.TextField(blank=True, verbose_name="Report"),
        ),
        migrations.AlterField(
            model_name="gentityevent",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enhydris.EventType",
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="gentityevent",
            name="user",
            field=models.CharField(blank=True, max_length=64, verbose_name="User"),
        ),
        migrations.AlterField(
            model_name="gentityfile",
            name="content",
            field=models.FileField(upload_to="gentityfile", verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="gentityfile",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="gentityfile",
            name="descr",
            field=models.CharField(max_length=100, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="gentityfile",
            name="remarks",
            field=models.TextField(blank=True, verbose_name="Remarks"),
        ),
        migrations.AlterField(
            model_name="gpoint",
            name="altitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Altitude"),
        ),
        migrations.AlterField(
            model_name="gpoint",
            name="original_srid",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Original SRID"
            ),
        ),
        migrations.AlterField(
            model_name="lentity",
            name="remarks",
            field=models.TextField(blank=True, verbose_name="Remarks"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="acronym",
            field=models.CharField(blank=True, max_length=50, verbose_name="Acronym"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(blank=True, max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="initials",
            field=models.CharField(blank=True, max_length=20, verbose_name="Initials"),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Middle names"
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="copyright_holder",
            field=models.TextField(verbose_name="Copyright holder"),
        ),
        migrations.AlterField(
            model_name="station",
            name="copyright_years",
            field=models.CharField(max_length=10, verbose_name="Copyright years"),
        ),
        migrations.AlterField(
            model_name="station",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_stations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Administrator",
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="station",
            name="is_automatic",
            field=models.BooleanField(default=False, verbose_name="Is automatic"),
        ),
        migrations.AlterField(
            model_name="station",
            name="maintainers",
            field=models.ManyToManyField(
                blank=True,
                related_name="maintaining_stations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Maintainers",
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="overseer",
            field=models.CharField(blank=True, max_length=30, verbose_name="Overseer"),
        ),
        migrations.AlterField(
            model_name="station",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_stations",
                to="enhydris.Lentity",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="timeseries",
            name="time_step",
            field=models.CharField(
                blank=True,
                help_text=(
                    'E.g. "10min", "H" (hourly), "D" (daily), "M" (monthly), "Y" '
                    "(yearly). More specifically, it's an optional number plus a unit, "
                    "with no space in between. The units available are min, H, D, M, "
                    "Y. Leave empty if the time series is irregular."
                ),
                max_length=7,
                verbose_name="Time step",
            ),
        ),
        migrations.AlterField(
            model_name="timeseries",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (100, "Raw"),
                    (150, "Processed"),
                    (200, "Checked"),
                    (300, "Regularized"),
                    (400, "Aggregated"),
                ],
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="timeseriesgroup",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Hidden"),
        ),
        migrations.AlterField(
            model_name="timeseriesgroup",
            name="name",
            field=models.CharField(
                blank=True,
                help_text=(
                    "In most cases, you want to leave this blank, and the name of the "
                    "time series group will be the name of the variable, such as "
                    '"Temperature". However, if you have two groups with the same '
                    "variable (e.g. if you have two temperature sensors), specify a "
                    "name to tell them apart."
                ),
                max_length=200,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="timeseriesgroup",
            name="precision",
            field=models.SmallIntegerField(
                help_text=(
                    "The number of decimal digits to which the values of the time "
                    "series will be rounded. It's usually positive, but it can be "
                    "zero or negative; for example, for humidity it is usually zero; "
                    "for wind direction in degrees, depending on the sensor, you "
                    "might want to specify precision -1, which means the value will "
                    "be 10, or 20, or 30, etc. This only affects the rounding of "
                    "values when the time series is retrieved; values are always "
                    "stored with all the decimal digits provided."
                ),
                verbose_name="Precision",
            ),
        ),
        migrations.AlterField(
            model_name="timeseriesgroup",
            name="remarks",
            field=models.TextField(blank=True, verbose_name="Remarks"),
        ),
        migrations.AlterField(
            model_name="timeseriesgroup",
            name="time_zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enhydris.TimeZone",
                verbose_name="Time zone",
            ),
        ),
        migrations.AlterField(
            model_name="timeseriesgroup",
            name="unit_of_measurement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enhydris.UnitOfMeasurement",
                verbose_name="Unit of measurement",
            ),
        ),
        migrations.AlterField(
            model_name="timeseriesgroup",
            name="variable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enhydris.Variable",
                verbose_name="Variable",
            ),
        ),
        migrations.AlterField(
            model_name="timezone",
            name="utc_offset",
            field=models.SmallIntegerField(verbose_name="UTC offset"),
        ),
        migrations.AlterField(
            model_name="unitofmeasurement",
            name="descr",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="unitofmeasurement",
            name="symbol",
            field=models.CharField(max_length=50, verbose_name="Symbol"),
        ),
        migrations.AlterField(
            model_name="variabletranslation",
            name="descr",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Description"
            ),
        ),
    ]
