# Generated by Django 2.2.17 on 2020-12-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris", "0104_remove_copyright_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timeseriesgroup",
            options={
                "ordering": ["gentity", "name"],
                "verbose_name": "Time series group",
                "verbose_name_plural": "Time series groups",
            },
        ),
    ]
