# Generated by Django 2.2.12 on 2021-01-04 08:32

from django.db import migrations, models


def convert_existing_processed(apps, schema_editor):
    Timeseries = apps.get_model("enhydris", "Timeseries")
    for timeseries in Timeseries.objects.filter(type=150):
        timeseries.type = 100
        timeseries.save()


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris", "0105_timeseries_group_ordering"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="timeseries",
            name="only_one_raw_or_processed_timeseries_per_group",
        ),
        migrations.AlterField(
            model_name="timeseries",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (100, "Initial"),
                    (200, "Checked"),
                    (300, "Regularized"),
                    (400, "Aggregated"),
                ],
                verbose_name="Type",
            ),
        ),
        migrations.AddConstraint(
            model_name="timeseries",
            constraint=models.UniqueConstraint(
                condition=models.Q(type=100),
                fields=("timeseries_group",),
                name="only_one_initial_timeseries_per_group",
            ),
        ),
        migrations.RunPython(convert_existing_processed),
    ]
