# Generated by Django 3.2.13 on 2022-10-15 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris", "0111_sitesdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="gentity",
            name="display_timezone",
            field=models.CharField(
                default="Etc/GMT",
                choices=[
                    ("Etc/GMT", "UTC"),
                    ("Etc/GMT+1", "UTC-1"),
                    ("Etc/GMT+2", "UTC-2"),
                    ("Etc/GMT+3", "UTC-3"),
                    ("Etc/GMT+4", "UTC-4"),
                    ("Etc/GMT+5", "UTC-5"),
                    ("Etc/GMT+6", "UTC-6"),
                    ("Etc/GMT+7", "UTC-7"),
                    ("Etc/GMT+8", "UTC-8"),
                    ("Etc/GMT+9", "UTC-9"),
                    ("Etc/GMT+10", "UTC-10"),
                    ("Etc/GMT+11", "UTC-11"),
                    ("Etc/GMT+12", "UTC-12"),
                    ("Etc/GMT-1", "UTC+1"),
                    ("Etc/GMT-2", "UTC+2"),
                    ("Etc/GMT-3", "UTC+3"),
                    ("Etc/GMT-4", "UTC+4"),
                    ("Etc/GMT-5", "UTC+5"),
                    ("Etc/GMT-6", "UTC+6"),
                    ("Etc/GMT-7", "UTC+7"),
                    ("Etc/GMT-8", "UTC+8"),
                    ("Etc/GMT-9", "UTC+9"),
                    ("Etc/GMT-10", "UTC+10"),
                    ("Etc/GMT-11", "UTC+11"),
                    ("Etc/GMT-12", "UTC+12"),
                    ("Etc/GMT-13", "UTC+13"),
                    ("Etc/GMT-14", "UTC+14"),
                ],
                help_text=(
                    "Time series timestamps are always stored in UTC. Select the "
                    "time zone for displaying timestamps of time series referring to "
                    "this object."
                ),
                max_length=50,
                verbose_name="Display time zone",
            ),
        ),
        migrations.AlterField(
            model_name="timeseriesgroup",
            name="time_zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enhydris.TimeZone",
                null=True,
            ),
        ),
    ]
