# Generated by Django 3.2.13 on 2022-10-16 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris", "0113_display_timezone_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeseriesgroup",
            name="time_zone",
        ),
        migrations.DeleteModel(
            name="TimeZone",
        ),
    ]
