# Generated by Django 3.2.18 on 2023-02-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enhydris', '0114_delete_timezone_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseriesgroup',
            name='public',
            field=models.BooleanField(default=False, help_text='Timeseries is available for public viewing and downloading data.'),
        ),
    ]
