# Generated by Django 3.2.18 on 2023-04-14 13:13

from django.conf import settings
from django.db import migrations, models

import enhydris.models.timeseries


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris", "0114_delete_timezone_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeseries",
            name="publicly_available",
            field=models.BooleanField(
                default=enhydris.models.timeseries.get_default_publicly_available,
                help_text=(
                    "Whether users who have not logged on have permission to download "
                    "the time series data."
                ),
                verbose_name="Publicly available",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="timeseries_data_viewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="viewing_stations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Time series data viewers",
                help_text="Users with permission to view time series data",
            ),
        ),
    ]
