# Generated by Django 5.2.4 on 2025-09-05 15:28

from django.db import migrations


def confirm_original_srid(apps, schema_editor):
    Gpoint = apps.get_model("enhydris", "Gpoint")
    for gpoint in Gpoint.objects.all():
        if (gpoint.original_srid is not None) and (gpoint.original_srid != 4326):
            raise RuntimeError(
                "This migration does away with Gpoint.original_srid. Cowardly "
                "refusing to proceed because at least one Gpoint has original_srid "
                "that is not None and is not 4326. This should not be a problem, but "
                "it's possible that you'd want to keep track of the original SRID "
                "(e.g. in the comments)."
            )


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris", "0118_aggregate_and_synoptic"),
    ]

    operations = [
        migrations.RunPython(
            confirm_original_srid, reverse_code=migrations.RunPython.noop
        )
    ]
