# Generated by Django 5.2.4 on 2025-09-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris", "0119_original_srid_confirmation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gpoint",
            name="original_srid",
        ),
    ]
