# Generated by Django 2.2.15 on 2020-10-20 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoprocess", "0101_squashed"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateOfChangeCheck",
            fields=[
                (
                    "checks",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="autoprocess.Checks",
                    ),
                ),
                (
                    "symmetric",
                    models.BooleanField(
                        help_text=(
                            "If this is selected, it is the absolute value of the "
                            "change that matters, not its direction. In this case, "
                            "the allowed differences must all be positive. If it's "
                            "not selected, only rates larger than a positive or "
                            "smaller than a negative difference are considered."
                        )
                    ),
                ),
            ],
            options={"db_table": "enhydris_autoprocess_rateofchangecheck"},
        ),
        migrations.CreateModel(
            name="RateOfChangeThreshold",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delta_t", models.CharField(max_length=6)),
                ("allowed_diff", models.FloatField()),
                (
                    "rate_of_change_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autoprocess.RateOfChangeCheck",
                    ),
                ),
            ],
            options={"db_table": "enhydris_autoprocess_rateofchangethreshold"},
        ),
    ]
