# Generated by Django 4.2.16 on 2024-12-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoprocess", "0105_pandas_frequency_specifiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aggregation",
            name="target_time_step",
            field=models.CharField(
                help_text=(
                    'E.g. "10min", "1h" (hourly), "1D" (daily), "1M" (monthly), '
                    '"1Y" (yearly). More specifically, it\'s a number plus a unit, '
                    "with no space in between. The units available are "
                    "min, h, D, M, Y."
                ),
                max_length=7,
                verbose_name="Target time step",
            ),
        ),
    ]
