# Generated by Django 5.2.4 on 2025-09-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoprocess", "0106_alter_aggregation_target_time_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="rateofchangecheck",
            name="remove_failing_values",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "If this is selected, records that fail the test will be set to "
                    "null, otherwise they will be left as is. In both cases, the "
                    "TEMPORAL flag will be applied to the affected records."
                ),
                verbose_name="Remove failing values",
            ),
            preserve_default=False,
        ),
    ]
